export const CREATE_TASK = "CREATE_TASK";

export const LOAD_TASKS_SUCCESS = "LOAD_TASKS_SUCCESS";

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";

export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

export const DELETE_TASK_OPTIMISTIC = "DELETE_TASK_OPTIMISTIC";
